"""empty message

Revision ID: 008efc6adc88
Revises: 62d903183bff
Create Date: 2024-03-13 17:22:52.280744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008efc6adc88'
down_revision = '62d903183bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=mysql.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('game_id',
               existing_type=sa.Text(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
