"""empty message

Revision ID: 2420aa75ba24
Revises: 7734a2d80bea
Create Date: 2024-04-08 18:22:24.307184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2420aa75ba24'
down_revision = '7734a2d80bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('console', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('timeslot', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('dateslot', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('booking_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('booking_ibfk_5', type_='foreignkey')
        batch_op.drop_column('console_id')
        batch_op.drop_column('time_id')
        batch_op.drop_column('game_id')
        batch_op.drop_column('date_id')

    with op.batch_alter_table('date_slot', schema=None) as batch_op:
        batch_op.alter_column('date_slot',
               existing_type=mysql.TIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_index('date_slot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_slot', schema=None) as batch_op:
        batch_op.create_index('date_slot', ['date_slot'], unique=True)
        batch_op.alter_column('date_slot',
               existing_type=sa.Date(),
               type_=mysql.TIME(),
               existing_nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('game_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('time_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('console_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('booking_ibfk_5', 'time_slot', ['time_id'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_4', 'date_slot', ['date_id'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_2', 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key('booking_ibfk_3', 'console', ['console_id'], ['id'])
        batch_op.drop_column('dateslot')
        batch_op.drop_column('timeslot')
        batch_op.drop_column('console')
        batch_op.drop_column('games')

    # ### end Alembic commands ###
