"""empty message

Revision ID: 545acb7d60fc
Revises: ef3c53f02fc6
Create Date: 2024-03-02 11:02:21.857468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '545acb7d60fc'
down_revision = 'ef3c53f02fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('console', schema=None) as batch_op:
        batch_op.add_column(sa.Column('console_name', sa.String(length=100), nullable=False))
        batch_op.drop_index('name')
        batch_op.drop_index('name_2')
        batch_op.drop_index('name_3')
        batch_op.create_unique_constraint(None, ['console_name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('console', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('name_3', ['name'], unique=True)
        batch_op.create_index('name_2', ['name'], unique=True)
        batch_op.create_index('name', ['name'], unique=True)
        batch_op.drop_column('console_name')

    # ### end Alembic commands ###
