"""empty message

Revision ID: 62d903183bff
Revises: 91a12cd98afe
Create Date: 2024-03-13 16:05:09.619926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62d903183bff'
down_revision = '91a12cd98afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_slot', schema=None) as batch_op:
        batch_op.alter_column('date_slot',
               existing_type=mysql.TIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_slot', schema=None) as batch_op:
        batch_op.alter_column('date_slot',
               existing_type=sa.Date(),
               type_=mysql.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
