"""empty message

Revision ID: 8cffa0905b0f
Revises: 545acb7d60fc
Create Date: 2024-03-11 15:55:11.947349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cffa0905b0f'
down_revision = '545acb7d60fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('console_id', sa.Integer(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'game', ['game_id'], ['id'])
        batch_op.create_foreign_key(None, 'console', ['console_id'], ['id'])
        batch_op.drop_column('game_selection')
        batch_op.drop_column('console_selection')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_default')
        batch_op.drop_column('default')
        batch_op.drop_column('permissions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('default', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.create_index('ix_roles_default', ['default'], unique=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('console_selection', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('game_selection', mysql.VARCHAR(length=30), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('console_id')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
