"""empty message

Revision ID: 91a12cd98afe
Revises: 8cffa0905b0f
Create Date: 2024-03-13 16:00:38.727403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91a12cd98afe'
down_revision = '8cffa0905b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_slot', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_slot')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('time_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'date_slot', ['date_id'], ['id'])
        batch_op.create_foreign_key(None, 'time_slot', ['time_id'], ['id'])
        batch_op.drop_column('comment')
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('time_id')
        batch_op.drop_column('date_id')

    op.drop_table('date_slot')
    # ### end Alembic commands ###
