"""empty message

Revision ID: e6beefe7ab33
Revises: 
Create Date: 2024-04-02 12:45:39.081543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6beefe7ab33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_game_id'), ['game_id'], unique=False)

    with op.batch_alter_table('date_slot', schema=None) as batch_op:
        batch_op.alter_column('date_slot',
               existing_type=mysql.TIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.drop_index('date_slot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('date_slot', schema=None) as batch_op:
        batch_op.create_index('date_slot', ['date_slot'], unique=True)
        batch_op.alter_column('date_slot',
               existing_type=sa.Date(),
               type_=mysql.TIME(),
               existing_nullable=False)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_game_id'))

    # ### end Alembic commands ###
